services:
  - type: worker
    name: pica-platform-testing
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PICA_SECRET_KEY
        sync: false
      - key: PICA_USER_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    disk:
      name: pica-storage
      mountPath: /data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
